//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Authors = new HashSet<Authors>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PublishedIn { get; set; }
    
        public virtual ICollection<Authors> Authors { get; set; }
    }
}
